language: java
sudo: false
os:
  - linux
jdk:
  - oraclejdk9
notifications:
  email:
    on_success: never

script: mvn clean verify

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
