language: java
sudo: false
os:
  - linux
jdk:
  - oraclejdk11
notifications:
  email:
    on_success: never

script: mvn clean verify

after_success:
  - mvn clean test jacoco:report coveralls:report
