version: '{build}'
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk9
  - cmd: SET PATH=C:\Program Files\Java\jdk9\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - mvn clean verify
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
