version: '{build}'
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk9
  - cmd: SET PATH=C:\Program Files\Java\jdk9\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build: off
build_script:
  - mvn clean verify
test_script:
  - mvn clean test
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
on_finish:
  - ps: |
      $pathToSearch = (Resolve-Path '.\target\surefire-reports')
      $pathArray=Get-ChildItem $pathToSearch -Filter "*.xml" -file | get-item | select Name, FullName
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $webclient = New-Object 'System.Net.WebClient'
      $pathArray | %  { try { $webclient.UploadFile($url, (Resolve-Path $_.FullName)) } catch { $_ } }


